dfds/selfservice-portal

src/src/pages/topics/SearchView.js

Minor quality of life update:
- Expanding topic details no longer remove capability information.
- Capability ID is a link to that capability.
This is only relevant on the Topics Page

Added linking and expanded info

---

src/src/SelfServiceApiClient.js
src/src/pages/capabilities/KafkaCluster/Consumer.js
src/src/pages/capabilities/KafkaCluster/Topic.js

closes https://github.com/dfds/cloudplatform/issues/1800
The list of consumers for a specific topic is only available
- when looking at topics under a specific capability (restriction set in this PR)
- when the logged in user has access to this capability (restriction set in the selfservice-API)
- when looking at the extended information for topics (restriction set in this PR)
Consumers are simply a list of strings, and are rendered as such.
Outstanding questions:
- Should we notify users on what constitutes a consumer (Kafka retention of some data may affect consumer count)?
- Can we live with the above restrictions for now? My idea was to see it in action where it is most critical before rolling things out throughout.
Depends on dfds/cloudplatform/issues/1799

Allow listing of consumers for topics one has access to

---

src/src/CapabilityCostsWrapper.js
src/src/components/BasicCapabilityCost/index.js
src/src/components/BasicCapabilityCost/style.module.css
src/src/pages/capabilities/MyCapabilities.js
src/src/pages/capabilities/myCapabilities.module.css

closes dfds/cloudplatform/issues/1903
Currently a cost curves are displayed to the right of capabilities in the My Capabilities section, however it is only displaying cost trends and not the actual costs, e.g. two curves might look the same but one capability could have costs 10 times higher than the other.
This PR adds an average cost for the period (7 days) displayed to the right of the cost curve like so:

Display cost text in My Capabilities

---

src/src/pages/capabilities/SelectedCapabilityContext.js
src/src/pages/capabilities/details.js

closes dfds/cloudplatform/issues/1955
Forgot to modify the frontend before considering the task closed.
On the overview page, all deleted capabilities will be highlighted with the warning icon, just the same as pending deletion. This is already in the code.
On the details page, the title will say 'Deleted'.
These are not perfect, but they are something to start with. Then we can see how the OPS teams use this newfound power and modify accordingly.

Indication of deletion

---

src/src/ErrorContext.js
src/src/ErrorDisplay.js
src/src/components/Toast/index.js
src/src/components/Toast/toast.module.css
src/src/errordisplay.module.css

closes dfds/cloudplatform/issues/1969 
A bit above and beyond, but I did not like our current stacked rendering of errors.
I am not happy with the management of transitions and would like inputs, as the current Toast-code is a bit messy.
* Toasts take an optional `details` property.
* Toasts with a detail property has a 'details'-button which opens a modal with the content of the details-property.
* Toasts are displayed in a list, instead of stacked on top of one another.
* Toasts fade in, fade out, and slide nicely down the list.
* Toasts are styled slightly nice (IMO).
* Cleanup of the styles used, as a lot of them were unnecessary.
* Toasts could offer different ways of rendering complext data in the details Modal.
* Absolute elements (like our toasts) does not work well with z-index …

Feature/1969: Error details and improved styling

---

src/src/pages/capabilities/capabilities.module.css
src/src/pages/capabilities/index.js
src/src/pages/topics/index.js
src/src/pages/topics/topic.module.css

closes dfds/cloudplatform/issues/2043
I am not happy about repeating stylings, but even in this case global stylings seem worse.
Neither am I happy with how the styling is currently set up, making this hack necessary, but fixing the DFDS frontend library is a massive task that could have more conequences than we want to deal with.
Lastly; using `!important` is a faux pas, but here we go -- it seems necessary here, unfortunately.

Layer splash image underneath popups

---

fake_dependencies/selfservice-api/package.json
src/package.json

The semver version should be used for the current dependencies, of which we have multiple in package-lock.
The react-scripts are a build tool and any issue therein are not an issue in production.
Moving this to dev-dependencies hopefully silences github's dependabot.

Fix warnings from dependabot

---

src/src/pages/capabilities/KafkaCluster/index.js

closes dfds/cloudplatform/issues/2177
temporary solution until we have fixed confluent cloud issue

disabled kafka cluster access for now

---

src/src/components/invitations/MyInvitations.js
src/src/pages/capabilities/index.js

closes dfds/cloudplatform/issues/2231
Should be fully reusable for future teams invitations (or other  invitations).

Initial invitations management view

---

src/src/components/Toast/toast.module.css
src/src/errordisplay.module.css

closes dfds/cloudplatform/issues/2232
Also let the toasts figure out their own size, as the details button was not properly contained with the 120px
It's hard to make image of the sticky-ness

Sticky Toasts. Om nom nom

---

.vscode/extensions.json
.vscode/settings.json
setup-pre-commit-hook.sh
setup-tooling.sh

closes dfds/cloudplatform/issues/2275
Would appreciate a hand testing if this works (if you are using vscode for this project)
With the changes made in this PR, vscode should sent you a notification when you open the project, asking you to install the prettier extension if it is not already installed.
It'll also override 2 of your global vscode settings for this project only:
- On file save it will automatically format your file
- It'll change the default formatter for all files in the project to prettier
If you don't already have prettier installed via npm, you can either run the setup-tooling.sh script in the root of the project directory or simple run `npm install --save-dev --save-exact prettier` while being inside the root of the project directory.

Add vscode project configs for formatting using prettier

---

src/src/pages/capabilities/costs/index.js

closes dfds/cloudplatform/issues/2296
See issue for no additional context: https://github.com/dfds/cloudplatform/issues/2296
Before:
After:

Re-enable finout link on Capablity page

---

src/src/pages/capabilities/MyCapabilities.js

closes dfds/cloudplatform/issues/2058
Before:
After:

Added css overflow to the appropriate elements, so the cost tooltip is not cut off

---

src/src/hooks/Topics.js
src/src/pages/capabilities/SelectedCapabilityContext.js

closes dfds/cloudplatform/issues/2301
Silly mistake that was never actually tested or was hidden by the fact that no error boxes was shown even though it failed.

Fixed ability update topic descriptions

---

src/package-lock.json
src/package.json
src/src/pages/capabilities/jsonmetadata/index.js

closes dfds/cloudplatform/issues/2314
- Ajv needs to use Ajv2020 in order to work with `"$schema": "https://json-schema.org/draft/2020-12/schema"` 
- `const addFormats = require("ajv-formats").default` added to handle `date-time` datatype

fixed validation of schema for new version

---

src/src/AppContext.js
src/src/Utils.js
src/src/hooks/Capabilities.js
src/src/pages/capabilities/NewCapabilityDialog.js
src/src/pages/capabilities/capabilityTags/index.js
src/src/pages/capabilities/details.js
src/src/pages/capabilities/index.js

closes dfds/cloudplatform/issues/2362
Capability auto reload is still broken, but is covered in another ticket (#2284).
As such I have not looked into that here, even though it very much is an issue.
Hopefully this is reusable and generic enough to serve for a while.

Use schema during capability creation and on details view

---

src/src/JsonSchemaContext.js
src/src/Utils.js
src/src/pages/capabilities/NewCapabilityDialog.js
src/src/pages/capabilities/capabilityTags/capabilityTagsSubForm.js
src/src/pages/capabilities/capabilityTags/index.js
src/src/pages/capabilities/details.js
src/src/pages/capabilities/jsonmetadata/index.js

closes dfds/cloudplatform/issues/2406
Issue was that fetching of the json schema happened inside of CapabilityTagsSubForm component, but this component was never shown (get executed), because no json schema was set:
```
return (
hasSchema && (
<>
<PageSection headline="Capability Tags">
<CapabilityTagsSubForm
title=""
setMetadata={setFormData}
setHasSchema={setHasSchema}
setValidMetadata={setIsValid}
preexistingFormData={existingFormData}
/>
``` 
I have moved json schema fetching and filtering into its own context that now replaces manual fetching around
Tested with:
- No schema
- Schema with no required properties
- Schema with required properties

refactored json schema fetching and using

---

src/src/JsonSchemaContext.js
src/src/pages/capabilities/capabilityTags/capabilityTagsSubForm.js
src/src/pages/capabilities/capabilityTags/index.js

closes dfds/cloudplatform/issues/2500
This is a draft, as it is just a suggestion still.
Further we should not roll this out until the underlying schema is in the right state.
Changes:
Render all tagging json schema properties instead of just required.
Required fields still block creation or updating, when not set.
This is a very simple way to keep some tags optional without changing their values.
Further work susggestions:
- Structure the tagging form to group required and optional tags.
- Have some text indicating what is missing before being able to click 'add' under New Capabilities.

Allow optional tags

---

src/src/pages/capabilities/KafkaCluster/MessageContracts.js

closes dfds/cloudplatform/issues/2533
Fix is to only show evolve button if there is a handler for it

disabled evolve button in topics page

---

src/src/pages/capabilities/costs/index.js

closes dfds/cloudplatform/issues/2540

If no cost centre is set, the UI should reflect this

---

src/src/pages/capabilities/SelectedCapabilityContext.js
src/src/pages/capabilities/capabilityAdoptionLevel/capabilityAdoptionLevel.module.css
src/src/pages/capabilities/capabilityAdoptionLevel/index.js
src/src/pages/capabilities/details.js
src/src/pages/capabilities/summary/index.js
src/src/pages/capabilities/summary/summary.module.css

closes dfds/cloudplatform/issues/2526
We need a better suggestion for how to indicate 'good', 'bad', 'neutral'.
JanV is not a fan of integer-scores, and quite focused on this ternary system.
Further more, he is 100% against showing an overall capability score, so I removed that for now.
But how do we improve the inherent understanding of what is needed.
Less powerful, but follows DFDS iconography, is less in your face, and is better for colour blindness 🤷‍♂️

Initial design for feedback

---

src/src/pages/capabilities/capabilityTags/capabilityTagsSubForm.js

closes dfds/cloudplatform/issues/2544
Sanitizing HTML removes `target='_blank'` as it is considered dangerous, granting access to the window.
I do not like this. However, the original argument still stands; We are (kind of, sort of, maybe) in control of the input and therefore we can accept this thing.
However, I believe we should figure out if all these hoops are worth keeping, simply in order to use the JsonSchemaForReact library.

Live life dangerously

---

src/src/App.js
src/src/components/GlobalMenu/GlobalMenu.jsx
src/src/pages/capabilities/OtherCapabilities.js
src/src/pages/capabilities/criticality.js

closes dfds/cloudplatform/issues/2597
Separate page for seeing capability criticality based on tagging.
Only visible to Cloud Engineers.
Also added a flag in AppContext for checking Cloud Engineering status of the logged in user.
I have missed this a few times.

Criticality subpage for Cloud Engineers

---

src/src/AppContext.js
src/src/pages/capabilities/NewCapabilityDialog.js
src/src/pages/capabilities/capabilityTags/capabilityTags.module.css
src/src/pages/capabilities/capabilityTags/capabilityTagsSubForm.js

closes dfds/cloudplatform/issues/2585
Improving the UX of this form turned out to be quiet complicated due to the third party library we use for the JasonSchema. @SEQUOIIA and I did some work around in order to visualise the error if the cost centre is not filled out. This is not the ideal solution but it was the best we could do for now. I am looking forward for suggestions how to improve it.

improved ux of the NewCapabilityDialog

---

src/src/pages/capabilities/KafkaCluster/MessageContractDialog.js

closes dfds/cloudplatform/issues/2634
Message Type doesn't allow you to use uppercase

Message type doesn't allow uppercase

---

src/src/hooks/Capabilities.js
src/src/pages/capabilities/resources/resourceInfoBadges/index.js

closes dfds/cloudplatform/issues/2968
This solution is not 'good', but we have a tight deadline.
We should not have hardcoded things like this in the API and the frontend, when we also manage tags via a different repository.
For now it does a thing, though

Manage required tags and warn about missing ones

---

src/src/pages/capabilities/resources/resourceInfoBadges/index.js

Users had to reload the page when updating tags, before they could create new azure resource groups.
The tags-checker always approved the first attempt at creation, which it shouldn't.
Those two have been fixed.

take into account updated metadata
