- azure-pipelines.yml
- src/src/pages/capabilities/KafkaCluster/NewTopicDialog.js
- src/src/pages/capabilities/NewCapabilityDialog.js
Also enforce restrictions in frontend.
> Update naming restrictions for capabilities and topics

- src/src/pages/capabilities/resources/index.js
Issue: https://github.com/orgs/dfds/projects/25/views/15?pane=issue&itemId=24110200
Screenshots showing the change:
> Added modal for seeing logs

- fake_dependencies/selfservice-api/src/routes/capabilities.ts
- fake_dependencies/selfservice-api/src/routes/kafkatopics.ts
- src/src/AppContext.js
- src/src/ErrorContext.js
- src/src/ErrorDisplay.js
- src/src/SelfServiceApiClient.js
- src/src/Utils.js
- src/src/components/Toast/index.js
- src/src/components/Toast/toast.module.css
- src/src/errordisplay.module.css
- src/src/hooks/Capabilities.js
- src/src/hooks/SelfServiceApi.js
- src/src/hooks/Topics.js
- src/src/index.js
- src/src/pages/capabilities/KafkaCluster/Topic.js
- src/src/pages/capabilities/KafkaCluster/index.js
- src/src/pages/capabilities/OtherCapabilities.js
- src/src/pages/capabilities/SelectedCapabilityContext.js
- src/src/pages/capabilities/index.js
- src/src/pages/frontpage/TopVisitors.js
- src/src/pages/topics/SearchView.js
- src/src/pages/topics/TopicsContext.js
- src/src/pages/topics/index.js
closes dfds/cloudplatform/issues/1704
> Error handling functionality 

- src/src/AppContext.js
- src/src/CapabilityCostsWrapper.js
- src/src/SelfServiceApiClient.js
- src/src/pages/capabilities/costs/costs.module.css
- src/src/pages/capabilities/costs/index.js
closes dfds/cloudplatform/issues/1895
This PR also contains fixing of a spellign mistake and fixing of incorrect getting of unix time in the capabilityWrapper.
> Replace finout link with coming soon message

- src/src/pages/capabilities/members/members.module.css
- src/src/pages/capabilities/members/profilepicture.js
- src/src/pages/capabilities/members/profilepicture.module.css
Issue: https://github.com/dfds/cloudplatform/issues/1906
Before:
After:
> Don't show img element if user doesn't have a profile picture

- src/src/components/BasicCapabilityCost/index.js
closes dfds/cloudplatform/issues/1909
Before
After
> Fix issue: NaN$/d

- src/src/components/PageSection/index.js
- src/src/pages/capabilities/KafkaCluster/index.js
- src/src/pages/capabilities/KafkaCluster/index.module.css
- src/src/pages/topics/index.js
Issue: https://github.com/dfds/cloudplatform/issues/1876
Before:
After:
---
Before:
After:
---
Before:
After:
> Include cluster id whenever cluster name is used

- src/src/AppContext.js
closes dfds/cloudplatform/issues/1983
I saw there was some code that is no longer used so I decided to clean it up :)
> Removing old code

- src/src/AppContext.js
- src/src/pages/capabilities/KafkaCluster/index.js
- src/src/pages/capabilities/SelectedCapabilityContext.js
closes dfds/cloudplatform/issues/1788
Minor code change, but seems to work
> Only poll topics when expecting change

- src/.env.production
- src/src/pages/frontpage/frontpage.module.css
- src/src/pages/frontpage/index.js
closes dfds/cloudplatform/issues/1956
https://github.com/dfds/selfservice-portal/assets/5738476/4ebbb7ec-a137-4077-bc64-fec93d115211
> added chat input that redirects user to ai chat

- src/src/pages/capabilities/OtherCapabilities.js
closes dfds/cloudplatform/issues/2024
None
> Description field is filled with name and not description

- src/package-lock.json
- src/package.json
- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/myCapabilities.module.css
https://github.com/dfds/cloudplatform/issues/1970
Replaced the old React Table with a custom one that has all special functionalities disabled (except sorting) in My Capabilities.
> new custom table for my capabilities

- src/src/pages/capabilities/MyCapabilities.js
> fixed error with the react table keys and the one with the empty header

- src/src/pages/ecr/index.js
> Fixed typo on ECR page

- src/src/components/Toast/index.js
- src/src/hooks/ECRRepositories.js
- src/src/pages/ecr/NewRepositoryDialog.js
- src/src/pages/ecr/index.js
closes dfds/cloudplatform/issues/2068
Also fixed the text in a prompt
> proper loading logic

- src/src/pages/capabilities/MyCapabilities.js
Just fixing a spelling mistake and cleaning up magical variables
> minimal cleanup and correction

- src/src/ErrorDisplay.js
- src/src/components/PageSection/PageSection.module.css
- src/src/components/PageSection/index.js
- src/src/pages/capabilities/AwsResourceCount/index.js
- src/src/pages/capabilities/KafkaCluster/index.js
- src/src/pages/capabilities/KafkaCluster/index.module.css
- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/NewCapabilityDialog.js
- src/src/pages/capabilities/SelectedCapabilityContext.js
- src/src/pages/capabilities/costs/index.js
- src/src/pages/capabilities/details.js
- src/src/pages/capabilities/index.js
- src/src/pages/capabilities/resources/index.js
- src/src/pages/capabilities/resources/resourceInfoBadges/index.js
closes dfds/cloudplatform/issues/1882
This is not a 'nice' PR, as it does way too much, but I decided against creating 4+ smaller ones.
I am happy to split this up if you feel like it.
Fixes
* Hacky solution to aws account requests (note 1)
* Fixed javascript errors from key-duplication
* Fixed html dom errors due to illegal nesting (div-tags in p-tags and the like).
* Minor wordings updated
* Hiding of interface elements when irrelevant (e.g. no costs when we do not have an AWS account)
Note 1)
The process of requesting an AWS account is a manual one in our production sense.
Polling for updates seems like a weird thing when it may take hours or even days for the process to complete.
For now it changes the state in the frontend and requires a reload to re-enquire the details from the …
> Spring cleaning part X

- src/src/pages/capabilities/AwsResourceCount/AwsCount.module.css
- src/src/pages/capabilities/AwsResourceCount/index.js
closes dfds/cloudplatform/issues/2085
John's suggestions were used for this.
On a personal note, I am not fond of very opinionated interfaces based on such little input, but let's try this out.
The addition of a little more information in the cards does help a bit, at least in my mind.
> More specific AWS count UI

- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/OtherCapabilities.js
closes dfds/cloudplatform/issues/2103
None
> Devil is in the details

- src/src/pages/capabilities/AwsResourceCount/index.js
closes dfds/cloudplatform/issues/2110
> now using material react table for resource counts modal

- src/src/ErrorContext.js
- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/OtherCapabilities.js
- src/src/pages/ecr/index.js
closes dfds/cloudplatform/issues/2147
This solution requires some setup for all tables and thus is not perfect by a long stretch.
However, it works -- which for now is the most important thing.
@HrisyToteva; Can you add this or similar to the topics-table that you are working on?
> once again with toast layering

- src/src/pages/capabilities/SelectedCapabilityContext.js
closes dfds/cloudplatform/issues/2151
> Wait for topic availability

- src/src/pages/capabilities/KafkaCluster/index.js
closes dfds/cloudplatform/issues/2183
None :)
> reverted request button back to working

- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/capabilities.module.css
closes dfds/cloudplatform/issues/2174
> indication of pending deletion of a topic

- src/src/hooks/Capabilities.js
- src/src/pages/capabilities/SelectedCapabilityContext.js
closes dfds/cloudplatform/issues/2201
useCapabilityMembersApplications hook has been created
> useCapabilityMembersApplications

- src/src/AppContext.js
- src/src/hooks/Profile.js
closes dfds/cloudplatform/issues/2212
new hook to load "/me" endpoint has been added.
> new hook for myProfile

- src/src/AppContext.js
- src/src/hooks/Profile.js
closes dfds/cloudplatform/issues/2214
new hook useStats
> new hook getStats

- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/OtherCapabilities.js
- src/src/pages/ecr/index.js
closes dfds/cloudplatform/issues/2109
The values for each table's default size are pure guess work.
> Initial suggested settings for pagination

- src/src/SelfServiceApiClient.js
- src/src/hooks/Profile.js
- src/src/pages/frontpage/TopVisitors.js
closes dfds/cloudplatform/issues/2228
new hook useTopVisiotors
> useTopVisitors

- src/src/MetricsWrapper.js
closes dfds/cloudplatform/issues/2246
none
> removed log line

- src/src/hooks/ECRRepositories.js
- src/src/pages/ecr/NewRepositoryDialog.js
- src/src/pages/ecr/index.js
closes dfds/cloudplatform/issues/2121
Update to match changes to API found [here](https://github.com/dfds/selfservice-api/pull/79/)
> Repositories should only have 1 name attribute

- src/src/App.js
- src/src/components/GlobalMenu/GlobalMenu.jsx
- src/src/hooks/Teams.js
- src/src/pages/capabilities/OtherCapabilities.js
- src/src/pages/teams/index.js
- src/src/pages/teams/teams.module.css
closes dfds/cloudplatform/issues/2197
much more clean than #113
> added teams page

- src/src/pages/capabilities/summary/index.js
> Better layout

- .github/workflows/check_pr_formatting.yaml
- Makefile
- azure-pipelines.yml
- src/src/components/invitations/MyInvitations.js
- src/src/pages/capabilities/index.js
closes dfds/cloudplatform/issues/2250
I also 'improved' the make file -- you opinion might vary
```
$ make
init:  Remove all generated files, install and update, and build
clean:  Remove all generated files
restore:  Install and update npm dependencies
check-node-version:  Verify node version dependencies
build:  Build and copy build artifacts over
container:  Build docker image
manifests:  Copy manifests over and update build number
ci:  Build from scratch
deliver:  Build from scratch and push containers
dev:  Run the portal locally, listening for updates
runcontainer:  Run the portal in a container
format:  Runs prettier
help:  Shows this list
```
> Improved make and new CI format check

- src/src/pages/capabilities/capabilityManagement/index.js
- src/src/pages/capabilities/details.js
closes dfds/cloudplatform/issues/2220
> Do not show management for deleted capabilities

- src/src/hooks/Capabilities.js
- src/src/hooks/Profile.js
- src/src/pages/capabilities/SelectedCapabilityContext.js
- src/src/pages/capabilities/details.js
closes dfds/cloudplatform/issues/2253
Backend changes: https://github.com/dfds/selfservice-api/pull/106
> Only load awsAccount if allowed by server

- src/src/hooks/Capabilities.js
- src/src/pages/capabilities/KafkaCluster/Topic.js
closes dfds/cloudplatform/issues/2267
> new hooks for consumers and message contacts

- src/src/pages/capabilities/KafkaCluster/MessageContractDialog.js
closes dfds/cloudplatform/issues/2245
None
> added error check for message contract type + auto insertion of dashes

- src/src/pages/capabilities/NewCapabilityDialog.js
closes dfds/cloudplatform/issues/2270
See issue https://github.com/dfds/cloudplatform/issues/2270 for more details
> Fix bug that stops creation of new Capability

- src/src/pages/frontpage/QuickLinks.js
feature/add-in-fin-ops-quick-link
closes #142
It would be great if we linked to this tool to increase the visibility :) should go to the login page
> Update QuickLinks.js to add in finout :)

- src/src/pages/capabilities/KafkaCluster/Topic.js
closes dfds/cloudplatform/issues/2244
Also closes dfds/cloudplatform/issues/2267
Added this fix to reduce conflicts
> now updates list of contracts when adding new contract

- src/src/pages/capabilities/NewCapabilityDialog.js
- src/src/pages/capabilities/details.js
closes dfds/cloudplatform/issues/2283
> disabled invitations

- src/src/pages/ecr/NewRepositoryDialog.js
closes dfds/cloudplatform/issues/2300
Dots are one thing, but this is currently broken in dev, due to our variable names (also fixed here).
I assume this originated from the merge-issues we saw back when we consolidated the naming.
> Fix variable naming issue and allow dots in names

- .vscode/settings.json
Should hopefully fix the weird .vscode/settings.json thing we encountered yesterday @HrisyToteva
> Added default formatter for JS files

- src/src/pages/capabilities/details.js
closes dfds/cloudplatform/issues/2285
> cannot add users to a capability that you are not member of

- src/src/pages/capabilities/invitations/index.js
closes dfds/cloudplatform/issues/2278
> 2278 bug invitations ability to invite any text

- src/src/pages/capabilities/invitations/index.js
closes dfds/cloudplatform/issues/2279
removed blue line of the invitations dropdown
> 2279 bug invitations blue line after clearing search suggestions

- src/src/pages/capabilities/capabilityInvitations/capabilityInvitations.js
closes dfds/cloudplatform/issues/2317
> renamed button for invitations

- src/src/components/DropDownMenu/index.js
- src/src/pages/capabilities/capabilities.module.css
- src/src/pages/capabilities/invitations/index.js
closes dfds/cloudplatform/issues/2315
Also some minor refactoring
> allow removal of users from invitee list

- src/src/pages/capabilities/capabilityInvitations/capabilityInvitations.js
- src/src/pages/capabilities/invitations/index.js
closes dfds/cloudplatform/issues/2324
read the issue for more context
> clear invitees after submitting

- src/src/pages/capabilities/capabilityInvitations/capabilityInvitations.js
- src/src/pages/capabilities/jsonmetadata/index.js
https://github.com/dfds/selfservice-portal/assets/58768740/af9fa09e-b34c-4f31-b794-47d3b0b4f0a0
> user feedback after invitations submition

- src/src/pages/capabilities/capabilityInvitations/capabilityInvitations.js
- src/src/pages/capabilities/details.js
- src/src/pages/capabilities/invitations/index.js
closes dfds/cloudplatform/issues/2280
the invite drop down does't show the existing members of the capability, so you cannot invite them again
> 2280 improvement invitations show which users have been invited and prevent them from being invited again

- src/src/Utils.js
closes dfds/cloudplatform/issues/2360
Example of my test code:
https://github.com/dfds/selfservice-portal/assets/5738476/1f4a9c0d-55ca-4a3b-a7f1-7e0c6d9b19e9
> added utils function for removing properties that are not required

- src/src/pages/capabilities/OtherCapabilities.js
closes dfds/cloudplatform/issues/2359
Is this good enough?
> i added the column

- src/src/App.js
- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/OtherCapabilities.js
- src/src/pages/capabilities/capabilities.module.css
- src/src/pages/capabilities/myCapabilities.module.css
closes dfds/cloudplatform/issues/2387
Also aligned the warning icon
> Truncate strings and align icon

- src/src/hooks/SelfServiceApi.js
closes dfds/cloudplatform/issues/2381
> check if response is json

- src/src/pages/capabilities/OtherCapabilities.js
closes dfds/cloudplatform/issues/2288
https://github.com/dfds/selfservice-portal/assets/5738476/be68fa4f-dc4c-4dda-af2a-510767617763
> addede new hidden column

- src/src/hooks/Capabilities.js
- src/src/pages/capabilities/SelectedCapabilityContext.js
- src/src/pages/capabilities/capabilityTags/index.js
closes dfds/cloudplatform/issues/2401
> changed capability tags to use required json metadata endpoint

- src/src/SelfServiceApiClient.js
- src/src/pages/capabilities/KafkaCluster/NewTopicDialog.js
closes dfds/cloudplatform/issues/2388
See issue for additional context https://github.com/dfds/cloudplatform/issues/2388
> Changed value used for infinite retention & parsing of retention values

- src/src/pages/capabilities/capabilityTags/capabilityTagsSubForm.js
closes dfds/cloudplatform/issues/2402
> added link to tagging policy

- src/src/pages/capabilities/capabilityTags/capabilityTagsSubForm.js
closes https://github.com/dfds/cloudplatform/issues/2457
> If no required fields, assume subform valid

- src/src/components/invitations/MyInvitations.js
closes dfds/cloudplatform/issues/2458
My capabilities table reloads after invitations acceptance
> My capabilities table reloads after invitations acceptance

- src/src/pages/capabilities/KafkaCluster/MessageContractDialog.js
closes dfds/cloudplatform/issues/2467
None
> force dfds envelope and add schemaVersion

- src/src/pages/capabilities/KafkaCluster/MessageContracts.js
- src/src/pages/capabilities/KafkaCluster/Topic.js
closes dfds/cloudplatform/issues/2509
Old: Not showing status correctly
New:
> fixed incorrect showing of headers incorrect count

- src/src/pages/capabilities/costs/finoutCostCentreLink.js
- src/src/pages/capabilities/costs/index.js
- src/src/pages/capabilities/details.js
closes dfds/cloudplatform/issues/2499
This is a hack.
It allows us to push Finout dashboards to The People.
Added some guiding text and merged the individual capability costs graph links into a single link. This was done as the individual links did not work quite as intended.
> Hack for adding some linkage to finout tribal dashboards

- src/src/Utils.js
closes dfds/cloudplatform/issues/2511
None
> made prettifying more robust

- src/src/pages/capabilities/MyCapabilities.js
closes dfds/cloudplatform/issues/2460
Also removed a shadow caused by overflow settings.
Our fetching of capabilities and the underlying logic is a tangled bunch at this point in time.
I think we could clean this up, but I believe that to be outside the scope of this bug.
If you think it belongs here, then I will look at it.
> Allow searching by AWS AccountId in MyCapabilities

- src/src/pages/capabilities/KafkaCluster/Topic.js
- src/src/pages/capabilities/KafkaCluster/Topics.module.css
closes dfds/cloudplatform/issues/2456
No screen shot due to timing issues.
Also remove the pointer-cursor from non-provisioned topics
> No expansion indication for nonprovisioned topics

- src/src/pages/capabilities/costs/index.js
closes dfds/cloudplatform/issues/2542
None
> Do string interpolation correctly

- src/src/pages/capabilities/KafkaCluster/MessageContract.module.css
- src/src/pages/capabilities/KafkaCluster/MessageContracts.js
closes dfds/cloudplatform/issues/2553
the frontend doesn’t allow you to evolve Messages Contracts that are not provisioned
> cannot evolve message contarcts that are not Provisioned

- src/src/pages/topics/rowDetails.js
closes dfds/cloudplatform/issues/2541
correct sorting of the message contracts by version in the topic page
> correct sorting of the message contarcts by version

- src/src/pages/topics/rowDetails.js
closes dfds/cloudplatform/issues/2545
Retry creation of a message contract fixed in the topic page
> retry creation of a message contract fixed in the topic page

- Makefile
- src/src/pages/capabilities/capabilityTags/capabilityTagsSubForm.js
- src/src/pages/capabilities/details.js
- src/tests/auth-globalsetup.js
- src/tests/parallel/capabilities.spec.js
JanV does not want this feature out in production; This removes the feature with easy reinsertion in mind.
The current solution lives up to our own definition of done, but this was not initially agreed with stakeholders (JanV).
JanV has a bunch of comments which must be discussed.
To make matters interesting, he is still formulating the minimal solution in the road map item.
In short: this process failed 🤷‍♂️
> remove recommendations from capaibility details

- src/src/pages/capabilities/KafkaCluster/MessageContracts.js
closes dfds/cloudplatform/issues/2564
See the issue for more information
> cannot evolve message contract if the latest version is not provisioned

- .github/workflows/frontend-tests.yaml
> Pull some of the dev images instead of building them every pipeline run

- src/src/pages/capabilities/capabilityAdoptionLevel/index.js
- src/src/pages/capabilities/details.js
* Link to wiki
* Remove suggestions to reduce clutter
We should really reconsider this whole wiki idea.
It smells like a hack, since we don't have UX and UI power.
edit: Jan wants the wiki; Jan now owns the wiki.
> Add guidance link and remove suggestions

- src/src/pages/capabilities/NewCapabilityDialog.js
closes dfds/cloudplatform/issues/2637
https://github.com/dfds/selfservice-portal/assets/58768740/aeefa21e-ae3c-4a20-ad14-9a1edd9c0bf8
> ux improve

- src/src/AppContext.js
- src/src/pages/capabilities/NewCapabilityDialog.js
- src/src/pages/ecr/NewRepositoryDialog.js
closes dfds/cloudplatform/issues/2586
> 2586 improve the ux of the new repository dialog

- src/src/pages/capabilities/KafkaCluster/NewTopicDialog.js
closes dfds/cloudplatform/issues/2587
> updated ux of the new topic page

- src/src/pages/capabilities/KafkaCluster/MessageContractDialog.js
closes dfds/cloudplatform/issues/2632
Replaced the third-party library function that was inserting a new field into the json schema with a custom one.
> 2632 bug message contracts json schema example doesnt always show up

- src/src/GraphApiClient.js
Search by user email for invitations is enabled
> search by user email for invitations

- src/src/AppContext.js
- src/src/components/GlobalMenu/GlobalMenu.jsx
- src/src/pages/capabilities/MyCapabilities.js
- src/src/pages/capabilities/OtherCapabilities.js
- src/src/pages/capabilities/criticality.js
closes dfds/cloudplatform/issues/2675
* enrich the objects before rendering, as this allows the library to trivially work with the data.
* A bit of cleanup
> enable better criticality filtering

- src/src/pages/capabilities/criticality.js
> QOL Criticality

- .github/workflows/frontend-tests.yaml
- src/src/pages/capabilities/MyCapabilities.js
- src/tests/auth-globalsetup.js
- src/tests/parallel/capabilities.spec.js
- src/tests/parallel/capability.spec.js
- src/tests/sequential/capability.spec.js
> remove capability overview stats for my capabilities

- src/src/hooks/MembershipApplications.js
- src/src/pages/capabilities/index.js
- src/src/pages/capabilities/membershipapplications/index.js
- src/src/pages/capabilities/membershipapplications/index.module.css
Issue: https://github.com/dfds/cloudplatform/issues/2929
Reject example:
https://github.com/user-attachments/assets/57564cea-f4ec-4af3-b198-818a058d5412
Approve example:
https://github.com/user-attachments/assets/49636ce3-6e12-49bb-9e03-b7ef7fd734b9
> Added MembershipApplicationsUserCanApprove component

- src/src/pages/capabilities/SelectedCapabilityContext.js
- src/src/pages/capabilities/resources/resourceInfoBadges/index.js
closes dfds/cloudplatform/issues/2965
> Reintroduce Azure logic

- src/src/pages/capabilities/capabilityTags/index.js
closes dfds/cloudplatform/issues/2823
Not pretty, but it works
> allow seeing tags, but only sometimes modify

- src/src/pages/capabilities/resources/resourceInfoBadges/index.js
Reverts dfds/selfservice-portal#302
> Revert "check for existing before using"

- src/src/pages/capabilities/resources/resourceInfoBadges/index.js
1) The popup guiding Azure RG creation was placed wrongly in the structure, preventing it if an AWS account was present
2) Changes default Azure RG environment to the next unused one in the list, where prod is the last
> Sensible default Azure RG environment and fixed popup visibility

- src/src/pages/capabilities/SelectedCapabilityContext.js
- src/src/pages/capabilities/resources/resourceInfoBadges/index.js
closes dfds/cloudplatform/issues/2972
None
Environment: https://internal.hellman.oxygen.dfds.cloud/ssu/dev-env/feature-reintroduce-vpc/
> Reintroduce the removed code

- src/package-lock.json
- src/src/pages/capabilities/resources/resourceInfoBadges/index.js
closes dfds/cloudplatform/issues/2984
Moved environment selection to a new creation popup.
Added requirement of 'having read' cloud guidelines before creating Azure Resource Groups. (https://wiki.dfds.cloud/en/architecture/adrs/which-cloud)
> redesign and guidance popup

- src/src/pages/capabilities/details.js
This needs a rework before we roll it out
> remove capability claims temporarily

- src/.env.production
> Set base URL for production builds

- src/src/pages/capabilities/MyCapabilities.jsx
closes dfds/cloudplatform/issues/3037
None
> cleanup of myCapabilities

- src/src/pages/capabilities/MyCapabilities.jsx
closes dfds/cloudplatform/issues/3037
Forgot this timeliness
> Fix loading order

- .snyk
closes dfds/cloudplatform/issues/3055
None
> no more snyk ignore as the files are already gone

- src/src/pages/capabilities/details.jsx
closes dfds/cloudplatform/issues/3056
Also moved some sections around for clarity
> Do not show Kafka Clusters unless an AWS account is connected

- src/src/pages/capabilities/metadataTabbedView/capabilityTags/capabilityTags.module.css
- src/src/pages/capabilities/metadataTabbedView/capabilityTags/capabilityTagsSubForm.jsx
An attempt, but not perfect.
Better now that it is live
Side note:
`.class > * {}` Oh how I love CSS magic
> let's make things look slightly better

- src/src/pages/capabilities/capabilityAdoptionLevel/index.jsx
- src/src/pages/capabilities/capabilityInvitations/capabilityInvitations.jsx
- src/src/pages/capabilities/details.jsx
- src/src/pages/capabilities/members/index.jsx
- src/src/pages/capabilities/membershipapplications/index.jsx
- src/src/pages/capabilities/selfAssessment/index.jsx
closes dfds/cloudplatform/issues/3061
- Also grouped Self-Assessments with the rest of Capability Health while I was at it
- It is now possible to delete membership applications even if you yourself have approved them previously.
> Reorder details page

- src/src/pages/capabilities/metadataTabbedView/capabilityTags/capabilityTags.module.css
> this is better

- src/src/pages/capabilities/OtherCapabilities.jsx
A quick fix to temporarily alleviate frustrations during searches
> show all capabilities in one single list

- src/src/GraphApiClient.js
- src/src/components/DropDownMenu/index.jsx
closes dfds/cloudplatform/issues/3119
We have no guarantee that all externals will have an email-like displayName as we are expecting here.
A follow up meeting must be booked to figure out the actual rules
> Show ad users without email

- src/src/components/GlobalMenu/GlobalMenu.jsx
closes dfds/cloudplatform/issues/3120
> Move specialized actions to dropdown

- src/src/AppContext.jsx
- src/src/AuthService.js
- src/src/SelfServiceApiClient.js
- src/src/components/GlobalMenu/GlobalMenu.jsx
- src/src/hooks/SelfServiceApi.js
- src/src/pages/capabilities/membershipapplications/index.jsx
- src/src/pages/capabilities/metadataTabbedView/capabilityTags/index.jsx
- src/src/pages/capabilities/metadataTabbedView/index.jsx
- src/src/preAppContext.jsx
- src/src/state/remote/queries/kafka.ts
- src/src/state/remote/queries/membershipApplications.ts
- src/src/state/remote/queries/selfassessments.ts
- src/src/state/remote/queries/stats.ts
- src/src/state/remote/query.ts
closes dfds/cloudplatform/issues/3131
What??? Who would have thought that naming matters
> variable naming 

- src/src/pages/capabilities/resources/index.jsx
- src/src/pages/capabilities/resources/resourceInfoBadges/index.jsx
> use working wiki link

- src/src/pages/capabilities/MyCapabilities.jsx
- src/src/pages/capabilities/costs/index.jsx
- src/src/state/remote/queries/platformdataapi.ts
> Migrated costs query to new remote state setup; Re-added Capabilies list costs column

- src/src/state/remote/queries/platformdataapi.ts
> Check if data returned is null

- nginx.conf
> Tweaked nginx cache control for improved browser compatibility

- src/src/pages/frontpage/QuickLinks.jsx
closes dfds/cloudplatform/issues/3159
> add link to azure ai guide to frontpage

- src/src/pages/capabilities/SelectedCapabilityContext.jsx
- src/src/pages/capabilities/index.jsx
- src/src/pages/capabilities/membershipapplications/index.jsx
- src/src/pages/capabilities/membershipapplications/myOutstandingApplications.jsx
- src/src/state/remote/queries/membershipApplications.ts
Part of https://github.com/dfds/cloudplatform/issues/2485
This is not pretty, but not bad.
It does indicate that we should rethink Tables, but we should do that when we rethink our UI-dependencies anyway.
> Add ability to delete own membership applications

- src/src/TrackingContext.jsx
- src/src/pages/capabilities/index.jsx
- src/src/pages/frontpage/QuickLinks.jsx
Also removed the frontpage link, as apparently we are not ready 🤷
> First click track for test

- src/src/pages/capabilities/resources/resourceInfoBadges/index.jsx
> fix: typo on capability resources

- src/src/pages/capabilities/Capabilities.jsx
Just making CodeScene happy ... maybe
> CodeScene happiness

- src/src/pages/capabilities/resources/resourceInfoBadges/index.jsx
Added a simple textual change to requesting AWS Account or Azure resource groups.
> Add tag reminder to resource request

- src/src/CreationWizard.jsx
- src/src/pages/capabilities/NewCapabilityWizard.jsx
> Update tag texts in creation wizard to improve clarity

- src/src/pages/capabilities/details.jsx
Sara will take the heat from John 🫨 
(this is just a minor beginning of our cleanup task)
> remove adoption level

- src/src/pages/capabilities/metadataTabbedView/index.jsx
> updated text for capability tags

- src/src/pages/capabilities/Capabilities.jsx
- src/src/pages/capabilities/NewCapabilityWizard.jsx
- src/src/pages/capabilities/capabilities.module.css
- src/src/pages/capabilities/summary/index.jsx
> Make the people sign

- src/src/constants/tagConstants.jsx
Making sure it matches https://github.com/dfds/selfservice-json-schemas/commit/0f68c130312606c93ec1340405299587bd51398b
> Updated allow costcentre values

- src/src/pages/capabilities/resources/resourceInfoBadges/index.jsx
- src/src/pages/capabilities/resources/resourceInfoBadges/resourceInfoBadges.module.css
Complaints have been raised that the interface was not clear.
Switch to react-select for a unified experience.
> use react-select

- src/src/pages/release-notes/editor/tiptap/components/tiptap-templates/simple/data/content.json
Tiptap dies hard but strangely when the default text is malformed.
> Update default text to be tiptap legal

- src/src/components/ConsumerLink/index.jsx
- src/src/pages/capabilities/KafkaCluster/MessageContracts.jsx
- src/src/pages/capabilities/KafkaCluster/Topic.jsx
- src/src/pages/capabilities/details.jsx
- src/src/pages/topics/index.jsx
- src/src/pages/topics/rowDetails.jsx
Maybe not perfect, but easy and working for now.
> Let's link people to Grafana for consumers

- src/src/pages/capabilities/resources/resourceInfoBadges/index.jsx
> actually send data
